select * from Curriculum
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Nauman','Aziz',21,'AAAA','nauman@aziz.com','Via Aziz 1','111111')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Edoardo','PogaTanto',26,'BBBB','edo@pogo.com','Via Mano 2','22222')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Massimo','Franzoso',22,'CCCC','max@franzoso.com','Via Moto 3','333333')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Luca','Gentilesca',25,'DDDD','luca@gent.com','Via Cuneo 4','444444')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Dragos','Brinzila',23,'EEEE','dra@brin.com','Via Moldavia 5','55555')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Federico','Marras',21,'FFFF','fede@marras.com','Via Mito 6','66666')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Florin','Gheliuc',23,'GGGG','flo@gheliuc.com','Via Romagna 7','77777')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Carmen','Capobianco',34,'HHHH','Carmen@capob.com','Via Kinder 8','888888')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Ale','Siculo',20,'IIII','ale@siculo.com','Via Sicily 9','99999')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Matteo','Tani',22,'JJJJ','matteo@tani.com','Via Matrix 10','101010')
Insert into Curriculum (nome,Cognome,Eta,Matricola,Email,Residenza,Telefono) values ('Alessandro','Qwerty',23,'KKKK','alessandro@qwerty.com','Via MSI 11','1121212')

sELECT * FROM EspLav
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2010,2015,'Assitense socio sanitario','Diploma',1)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2004,2009,'Liceo Scientifico','Diploma',2)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2011,2016,'Scientifico tecnologico','Diploma',3)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2008,2013,'Geometra','Diploma',4)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2011,2016,'Ragioniere Programmatore','Diploma',5)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2012,2017,'Scientifico tecnologico','Diploma',6)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2010,2016,'Scientifico tecnologico','Diploma',7)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2002,2007,'Scientifico','Diploma',8)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2012,2017,'Ragioniere Programmatore','Diploma',9)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2010,2015,'Scientifico Matematico','Diploma',10)
Insert into EspLav (AnnoI,AnnoF,DESCRIZIONE,Qualifica,idCV) values (2010,2017,'Designer','Diploma',11)

Select * from Competenze
Insert into Competenze (tipo,Livello,IdCv) values ('Java',10,1)
Insert into Competenze (tipo,Livello,IdCv) values ('Pogo',8,2)
Insert into Competenze (tipo,Livello,IdCv) values ('Mangiare',9,3)
Insert into Competenze (tipo,Livello,IdCv) values ('Cunese',10,4)
Insert into Competenze (tipo,Livello,IdCv) values ('Boh',7,5)
Insert into Competenze (tipo,Livello,IdCv) values ('Camicia Bianca',8,6)
Insert into Competenze (tipo,Livello,IdCv) values ('Albanese',4,7)
Insert into Competenze (tipo,Livello,IdCv) values ('DataBase',10,8)
Insert into Competenze (tipo,Livello,IdCv) values ('Siculo',10,9)
Insert into Competenze (tipo,Livello,IdCv) values ('Matrici',8,10)
Insert into Competenze (tipo,Livello,IdCv) values ('Puntualita',6,11)


Select * from PercorsoStudi
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2013,2014,'Rosario','Ciao amico prendi rosa',1)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2000,2018,'Pogataro','Ho pogato un sacco',2)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2011,2014,'Motociclista','Una volta ho fatto un incidente',3)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2011,2012,'Motociclista','Uso la moto solo a cuneo',4)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2009,2017,'Niente','Non sapevo cosa scrivere',5)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2013,2014,'Motociclista','Ho il motorino',6)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2010,2016,'Giocatore','Forza Giaguari',7)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2003,2017,'Impiegata','L azienda è fallita',8)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2016,2018,'Programmatore','Ho fatto tutte cose',9)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2013,2018,'Matematico','Amo le matrici',10)
iNSERT INTO PercorsoStudi (AnnoI,AnnoF,Titolo,Descrizione,IdCv) values (2013,2014,'CollezionaDiplomi','Ho gia lavorato',11)